router1:
  interfaces:
    - name: ethernet-1/11
      description: "router1_to_router2"
      ipv4-prefix: "10.0.0.5/30"
    - name: ethernet-1/12
      description: "router1_to_router3"
      ipv4-prefix: "10.0.0.14/30"

router2:
  interfaces:
    - name: ethernet-1/11
      description: "router2_to_router3"
      ipv4-prefix: "10.0.0.9/30"
    - name: ethernet-1/12
      description: "router2_to_router1"
      ipv4-prefix: "10.0.0.6/30"

router3:
  interfaces:
    - name: ethernet-1/11
      description: "router3_to_router1"
      ipv4-prefix: "10.0.0.13/30"
    - name: ethernet-1/12
      description: "router3_to_router2"
      ipv4-prefix: "10.0.0.10/30"
