updates:
{{ $target := index .Vars .TargetName }}
{{- range $interface := index $target "interfaces" }}
  - path: "/interface[name={{ index $interface "name" }}]"
    value:
      admin-state: enable
      description: {{ index $interface "description" | default "" }}
      subinterface:
        - index: 0
          admin-state: enable
          ipv4:
            admin-state: enable
            address:
              - ip-prefix: {{ index $interface "ipv4-prefix" }}
  - path: "/network-instance[name=default]"
    value:
      interface:
        name: {{ index $interface "name" }}{{".0"}}

  - path: /network-instance[name=default]/protocols/ospf
    value:
      instance:
      - name: default
        router-id: {{ index $target "router-id" }}
        version: ospf-v2
        admin-state: enable
        area:
        - area-id: 0.0.0.0
          interface:
          - admin-state: enable
            interface-name: ethernet-1/11.0
          - admin-state: enable
            interface-name: ethernet-1/12.0
          - admin-state: enable
            interface-name: ethernet-1/21.0
{{- end }}

