subinterface:
- config:
    description: []
    enabled:
    - "true"
    index:
    - "0"
  ipv4:
    addresses:
      address:
      - config:
          ip: []
          prefix-length: []
          type:
          - PRIMARY
        vrrp:
          vrrp-group:
          - config:
              accept-mode:
              - "false"
              advertisement-interval:
              - "100"
              preempt:
              - "true"
              preempt-delay:
              - "0"
              priority:
              - "100"
              virtual-address: []
              virtual-router-id: []
            interface-tracking:
              config:
                priority-decrement:
                - "0"
                track-interface: []
    config:
      dhcp-client:
      - "false"
      enabled:
      - "true"
      mtu: []
    neighbors:
      neighbor:
      - config:
          ip: []
          link-layer-address: []
    proxy-arp:
      config:
        mode:
        - DISABLE
    unnumbered:
      config:
        enabled:
        - "false"
      interface-ref:
        config:
          interface: []
          subinterface: []
  ipv6:
    addresses:
      address:
      - config:
          ip: []
          prefix-length: []
          type:
          - GLOBAL_UNICAST
        vrrp:
          vrrp-group:
          - config:
              accept-mode:
              - "false"
              advertisement-interval:
              - "100"
              preempt:
              - "true"
              preempt-delay:
              - "0"
              priority:
              - "100"
              virtual-address: []
              virtual-link-local: []
              virtual-router-id: []
            interface-tracking:
              config:
                priority-decrement:
                - "0"
                track-interface: []
    autoconf:
      config:
        create-global-addresses:
        - "true"
        create-temporary-addresses:
        - "false"
        temporary-preferred-lifetime:
        - "86400"
        temporary-valid-lifetime:
        - "604800"
    config:
      dhcp-client:
      - "false"
      dup-addr-detect-transmits:
      - "1"
      enabled:
      - "true"
      mtu: []
    neighbors:
      neighbor:
      - config:
          ip: []
          link-layer-address: []
    router-advertisement:
      config:
        interval: []
        lifetime: []
        managed:
        - "false"
        other-config:
        - "false"
        suppress:
        - "false"
      prefixes:
        prefix:
        - config:
            disable-advertisement: []
            disable-autoconfiguration: []
            enable-onlink: []
            preferred-lifetime: []
            prefix: []
            valid-lifetime: []
    unnumbered:
      config:
        enabled:
        - "false"
      interface-ref:
        config:
          interface: []
          subinterface: []
  vlan:
    config:
      vlan-id: []
    egress-mapping:
      config:
        tpid: []
        vlan-id: []
        vlan-stack-action: []
    ingress-mapping:
      config:
        tpid: []
        vlan-id: []
        vlan-stack-action: []
    match:
      double-tagged:
        config:
          inner-vlan-id: []
          outer-vlan-id: []
      double-tagged-inner-list:
        config:
          inner-vlan-ids: []
          outer-vlan-id: []
      double-tagged-inner-outer-range:
        config:
          inner-high-vlan-id: []
          inner-low-vlan-id: []
          outer-high-vlan-id: []
          outer-low-vlan-id: []
      double-tagged-inner-range:
        config:
          inner-high-vlan-id: []
          inner-low-vlan-id: []
          outer-vlan-id: []
      double-tagged-outer-list:
        config:
          inner-vlan-id: []
          outer-vlan-ids: []
      double-tagged-outer-range:
        config:
          inner-vlan-id: []
          outer-high-vlan-id: []
          outer-low-vlan-id: []
      single-tagged:
        config:
          vlan-id: []
      single-tagged-list:
        config:
          vlan-ids: []
      single-tagged-range:
        config:
          high-vlan-id: []
          low-vlan-id: []
